apiVersion: v1
kind: ConfigMap
metadata:
  name: movieflixapp
  namespace: lambdasys-movieflix
data:
  DATABASE_SERVER_NAME: "postgres"
  DATABASE_USER_NAME: "movieflixapp"
  DATABASE_USER_PASSWORD: "movieflixapp_pwd"
#  JAVA_OPTS: "--enable-preview -agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n -XX:MaxRAMPercentage=80"
  JAVA_OPTS: "-XX:MaxRAMPercentage=80"
